from __future__ import annotations

from enum import Enum


class ReasonCode(str, Enum):
    # Success / informational
    DQSN_OK = "DQSN_OK"
    DQSN_SIGNAL_AGGREGATED = "DQSN_SIGNAL_AGGREGATED"

    # Fail-closed errors (contract / schema)
    DQSN_ERROR_INVALID_REQUEST = "DQSN_ERROR_INVALID_REQUEST"
    DQSN_ERROR_SCHEMA_VERSION = "DQSN_ERROR_SCHEMA_VERSION"
    DQSN_ERROR_COMPONENT_MISMATCH = "DQSN_ERROR_COMPONENT_MISMATCH"
    DQSN_ERROR_UNKNOWN_TOP_LEVEL_KEY = "DQSN_ERROR_UNKNOWN_TOP_LEVEL_KEY"

    # Fail-closed errors (payload hardening)
    DQSN_ERROR_SIGNALS_REQUIRED = "DQSN_ERROR_SIGNALS_REQUIRED"
    DQSN_ERROR_SIGNAL_INVALID = "DQSN_ERROR_SIGNAL_INVALID"
    DQSN_ERROR_SIGNAL_TOO_MANY = "DQSN_ERROR_SIGNAL_TOO_MANY"
    DQSN_ERROR_PAYLOAD_TOO_LARGE = "DQSN_ERROR_PAYLOAD_TOO_LARGE"
    DQSN_ERROR_BAD_NUMBER = "DQSN_ERROR_BAD_NUMBER"
